FROM fedora:latest

LABEL MAINTAINER Richard Lochner, Clone Research Corp. <lochner@clone1.com> \
      org.label-schema.name = "systemd" \
      org.label-schema.description = "Minimal linux systemd base container." \
      org.label-schema.vendor = "Clone Research Corp" \
      org.label-schema.usage = "https://github.com/lochnerr/systemd" \
      org.label-schema.vcs-url = "https://github.com/lochnerr/systemd.git"

# Manditory packages:
# systemd-container - systemd for containers.

# Useful packages for debugging:
# iproute - ip (used in provisioning and automated tests)
# procps-ng - ps (Needed to determine if running under systemd)
# wget - wget (used to get current named.cache file from internet)
# hostname - hostname (used in samba-set-vars)
# iputils - ping
# net-tools - ifconfig
# findutils - find

RUN dnf -y install --nodocs \
        systemd-container \
        iproute \
        procps-ng \
        wget \
        hostname \
        iputils \
        net-tools \
        findutils \
        && \
    systemctl mask \
       systemd-logind.service \
       systemd-resolved.service \
       systemd-oomd.service \
       && \
    # The cleanup cleans at least 80 MB from images as of 2024-09.
    # Not doing it, however, saves a lot of time on first dnf command.
    dnf -y clean all && \
    # Empty the yum cache.
    rm -rf /var/cache/dnf && \
    rm -rf /var/cache/yum && \
    true

# Use systemd init to bring up services.
CMD [ "/sbin/init" ]

# Copy the script files and other artifacts.
COPY bin/. /usr/local/bin/

# Set systemd stop signal.
STOPSIGNAL SIGRTMIN+3

# Set the build labels.
# Do this last to allow build cacheing during development.
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date = $BUILD_DATE \
      org.label-schema.vcs-ref = $VCS_REF

